**1.What is a Python library? Why do we use Python libraries?**

 Python library is a collection of modules, which are essentially Python files with a .py extension, that provide reusable code for various functionalities. These libraries can include functions, classes, and variables that allow you to perform many actions without writing your code.
 
We use Python libraries for several reasons:

Efficiency: Libraries often contain optimized code for complex operations, making your programs run more efficiently.
Code Reusability: Instead of writing code from scratch, you can use pre-written, tested, and optimized code, saving time and effort.
Simplicity: Libraries often have user-friendly interfaces, making complex tasks simpler.
Community Support: Popular Python libraries are maintained by a community of developers, ensuring they stay up-to-date and receive bug fixes.

**2.What is the difference between Numpy array and List?**

Memory Usage: Numpy arrays are more memory-efficient than lists. This means that they can store more data than lists for the same amount of memory.

Performance: Numpy arrays are faster and more performance-efficient than lists when it comes to mathematical and scientific computations.

Functionality: Numpy arrays offer several functions that are optimized for array computations, making them more suitable for mathematical operations. Lists, however, have a variety of built-in methods for different purposes, making them more versatile for general use cases.

Homogeneity: Numpy arrays are homogeneous, meaning they can only contain items of the same data type. Lists, on the other hand, are heterogeneous and can contain items of different data types.

Size Flexibility: The size of a Numpy array is fixed at the time of creation, whereas a list’s size can be changed (elements can be added or removed).

**3.Find the shape, size and dimension of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np
# Define the array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Get the shape of the array
shape = array.shape

# Get the size of the array
size = array.size

# Get the dimension of the array
dimension = array.ndim

print("Shape of the array: ", shape)
print("Size of the array: ", size)
print("Dimension of the array: ", dimension)

Shape of the array:  (3, 4)
Size of the array:  12
Dimension of the array:  2


 **4.Write python code to access the first row of the following array**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:

# Define the array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Access the first row of the array
first_row = array[0]

print("First row of the array: ", first_row)

First row of the array:  [1 2 3 4]


**5. How do you access the element at the third row and fourth column from the given numpy array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
# Define the array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = array[2,3]

print("Element at the third row and fourth column: ", element)

Element at the third row and fourth column:  12


**6.Write code to extract all odd-indexed elements from the given numpy array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
# Define the array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = array[::2, 1::2]

print("Odd-indexed elements: ", odd_indexed_elements)

Odd-indexed elements:  [[ 2  4]
 [10 12]]


**7.How can you generate a random 3x3 matrix with values between 0 and 1?**

In [14]:
# Generate a random 3x3 matrix with values between 0 and 1
matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:\n", matrix)

Random 3x3 matrix:
 [[0.67413918 0.84208325 0.25684087]
 [0.88942656 0.12971116 0.2268938 ]
 [0.53102035 0.39652999 0.44328739]]


**8.Describe the difference between np.random.rand and np.random.randn**

np.random.rand: This function generates random numbers from a uniform distribution in the range [0, 1). In a uniform distribution, all numbers in the specified range are equally likely to be generated.

np.random.randn: This function generates random numbers from a standard normal (Gaussian) distribution with mean 0 and variance 1. In a standard normal distribution, numbers close to the mean (in this case 0) are more likely to be generated.

**9. Write code to increase the dimension of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
# Define the array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase the dimension of the array
array_new_dim = array[np.newaxis, :]

print("Array with increased dimension:\n", array_new_dim)

Array with increased dimension:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [19]:
array.shape,array_new_dim.shape

((3, 4), (1, 3, 4))

**10. How to transpose the following array in NumPy?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [22]:
# Define the array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array rows become column and vice versa
transposed_array = array.T

print("Transposed array:\n", transposed_array)

Transposed array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**11.Consider the following matrix:**

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

1.perform the following 

2.index wise multiplication

3.matrix multiplication

4.add both the matrics

5.subtract matrix B from A

6.divide matrix B by A

In [24]:
 #Define the matrices
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise (element-wise) multiplication
index_wise_multiplication = A2 * B2

# Matrix multiplication
# For matrix multiplication, we need square matrices. So, let's take the first 3x3 part of A2 and B2.
matrix_multiplication = A2[:3, :3] @ B2[:3, :3]

# Add both the matrices
addition = A2 + B2

# Subtract matrix B from A
subtraction = A2 - B2

# Divide matrix B by A
# To avoid division by zero, we'll add a small constant to A2
division = B2 / (A2 + 1e-7)

print("Index-wise multiplication:\n", index_wise_multiplication)
print("\nMatrix multiplication:\n", matrix_multiplication)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nDivision:\n", division)

Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
 [[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]

Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division:
 [[0.9999999  0.99999995 0.99999997 0.99999998]
 [0.99999998 0.99999998 0.99999999 0.99999999]
 [0.99999999 0.99999999 0.99999999 0.99999999]]


 **12.Which function in Numpy can be used to swap the byte order of an array?**

byteswap() method to swap the byte order of an array1. This method toggles between low-endian and big-endian data representation by returning a byteswapped array1. 

In [26]:
# Define the array
array = np.array([1, 256, 8755], dtype=np.int16)

# Swap the bytes of the array elements
swapped_array = array.byteswap()

print("Swapped array: ", swapped_array)

Swapped array:  [  256     1 13090]


**13.What is the significance of the np.linalg.inv function?**



The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. The multiplicative inverse of a matrix is a crucial concept in linear algebra and has many applications in fields like machine learning, physics, and engineering.

Given a square matrix A, the function np.linalg.inv(A) returns a matrix B such that the dot product of A and B (and B and A) equals the identity matrix. In mathematical terms, if A is the original matrix and B is the inverse, then A @ B = B @ A = I, where I is the identity matrix, and @ represents matrix multiplication.

However, not all matrices have an inverse. A matrix has an inverse only if it is square (i.e., has the same number of rows and columns) and its determinant is not zero. If these conditions are not met, np.linalg.inv will raise a LinAlgError.

In [28]:
# Define a 2x2 matrix
A = np.array([[4, 7], [2, 6]])

# Compute the inverse of the matrix
B = np.linalg.inv(A)

print("Matrix A:\n", A)
print("\nInverse of A:\n", B)

Matrix A:
 [[4 7]
 [2 6]]

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


**14.What does the np.reshape function do, and how is it used**

The np.reshape function in NumPy is used to change the shape of an array without altering its data. The new shape should be compatible with the original shape.

In [29]:
# Define a 2x2 matrix
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Reshape the array to a 1-D array of length 8
B = np.reshape(A, 8)

print("Original array:\n", A)
print("\nReshaped array:\n", B)

Original array:
 [[1 2 3 4]
 [5 6 7 8]]

Reshaped array:
 [1 2 3 4 5 6 7 8]


**15. What is broadcasting in Numpy?**

Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. It eliminates the need to create explicit copies of arrays to match their shapes, making code more efficient and easier to write.


Basic Concept
Broadcasting works by virtually replicating the smaller array along the larger array so that they have compatible shapes for element-wise operations. This is done without actually making multiple copies of the data, which saves memory and improves performance.

Rules for Broadcasting
Trailing dimensions of size 1: If two arrays have different shapes, NumPy compares their shapes element-wise starting from the trailing dimensions. If the shapes are not equal, NumPy tries to stretch the dimensions with size 1 to match the other array.

One of the dimensions is 1: If one of the dimensions of an array is 1, it can be stretched to match the corresponding dimension of the other array.

Compatible shapes: Two shapes are compatible for broadcasting if for each dimension pair, they are either equal, or one of them is 1.